- name: variables at prompt
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: please enter course name
      private: false
    - name: DURATION
      prompt: please enter duration
      private: false
    - name: TRAINER
      prompt: please enter your trainer name
      private: false
  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "i am learning {{COURSE}} at {{TRAINER}} FOR {{DURATION}} "
         