- name: task level variables
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: please enter course name
      private: false
    - name: DURATION
      prompt: please enter duration
      private: false
    - name: TRAINER
      prompt: please enter your trainer name
      private: false
  vars:
    COURSE: "aws"
    TRAINER: "SIVA"
    DURATION: "THREE MONTHS"
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "i am learning {{COURSE}} trainer{{TRAINER}} duration{{DURATION}}"

    - name: print information again
      vars:
        COURSE: "DEVOPS"
        TRAINER: "KUMAR"
        DURATION: "FOUR MONTHS"
      ansible.builtin.debug:
        msg: "i am learning {{COURSE}} FOR {{DURATION}} AT {{TRAINER}}"  

    - name: printing information again and again
      ansible.builtin.debug:
        msg: "i am learning {{COURSE}} FOR {{DURATION}} AT {{TRAINER}}"  