- name: print info using loop
  hosts: local
  connection: local
  tasks:
   - name: print information
     ansible.builtin.debug:
      msg: "hello {{item}}"
     loop:
      - world
      - india
      - world
      - hyderabad    