- name: installing packages
  hosts: local
  connection: local
  tasks:
   - name: install package
     ansible.builtin.package:
       name: {{item}}
       state: present
  loop:
  - mysql
  - nginx
  - postfix
  - httpd     