- name: installing packages
  hosts: [web]
  tasks:
   - name: install packages
     ansile.builtin.package:
       name: "{{item}}"
       state: present
     loop:
      - mysql
      - nginx
      - nodejs        