- name: demo of filters or functions
  hosts: local
  connection: local
  tasks:
  
  - name: print default variable
    ansible.builtin.debug:
     msg: "hello {{world | default('india')}}"
  
  
  - name: convert to uppercase
    vars:
     greeting: "hello world"
    ansible.builtin.debug:
     msg: "{{greeting | upper}}"   
  
  
  - name: convert to lower case
    vars:
     greeting: "hAIII I AM SORRY"
    ansible.builtin.debug:
     msg: "{{greeting | lower}}"
  
  - name: get the unique value
    vars:
     numbers: [1 2 3 44 55 55 99 99 00]
    ansible.builtin.debug:
     msg: "{{numbers | unique}}"


  - name: get the min and max numbers
    vars:
     numbers: [11 22 3366 99 100] 
    ansible.builtin.debug:
     msg: " Min: {{ numbers | min }}, Max: {{ numbers | max}} "


  - name: convert map to list
    vars:
     COURSE: 
      name: 'Devops and aws'
      duration: 120 hours
      trainer: "siva kumar"
    ansible.builtin.debug:
     msg: "{{ COURSE | dict2items }}"

  - name: convert list to map
    vars:
       course:
       - { "key": "name","value": "DevOps with AWS" }
       - { "key": "duration","value": "120hours" }
       - { "key": "tainer","value": "siva kumar" }    
    ansible.builtin.debug:
     msg: "{{ course | items2dict }}"     


  - name: check ip address
    vars:
     myip: 123.12.123
    ansible.builtin.debug:
     msg: "{{ myip | ansible.utils.ipv4 }}"     
