- name: create route53 ec2 instances
  hosts: local
  connection: local
  vars:
   subnet_id: subnet-044dc3e24a0f7cd81
   ami_id: "ami-09c813fb71547fc4f"
   sg_id: "sg-01eb7fe97aa035d21"
   instances:
     - mysql
     - backend
     - frontend
   zone: prameela.online
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     vpc_subnet_id: "{{ subnet_id }}"
     instance_type: "t2.micro"
     security_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
   loop: "{{ instances }}"
   register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
     msg: "{{ ec2_instances }}"


  - name: create route 53 records 
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.daws81s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"


  - name: create route 53 records public ip
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.daws81s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"

